### ISSUE TITLE
want to have the URL

### ISSUE THREAD

**Issue by kunkun0w0** [pit-ray/SPADE-pix2pix-for-Anime#1]
Your results are so amazing.
I can't wait to try to run your model.
So when release the URL?|･ω･｀)

**Comment by pit-ray** [comment]
I prepared a script to download pre-trained weights of Generator and Discriminator.  You can get them by executing the following command.
```
python get_pretrained_weight.py
```

The model predicts from segment label and color hair. Please prepare 256 x 256 png annotated images and 256 x 256 filled hair color. You have to concatenate these and locate them into `predict_from`.  And, do the next script.  
```
python predict.py  
```
